### ISSUE TITLE
[Request] Update to latest Astro Version

### ISSUE THREAD

**Issue by linuxmobile** [inkdropapp/inkdrop-blog-template#1]
DevasLife, I wanted to ask you, if it is possible for you to update the template to the most current version of `Astro ^2.0`. So you give us an idea of how to use the template with `/Content` folder. And how to include it replacing "`Frontmatter`".

**Comment by craftzdog** [comment]
Thanks linuxmobile for bringing this to my attention.
Yeah, I would like to update the template once I get time to work on it after updating the desktop app!
